routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
Route::get('/admin-template', function() {
    return view('admin_template');
});

Route::get('/admin', function() {
    return view('base.admin');
});

Route::get('/admin-login', function() {
    return view('base.admin-login');
});

Route::get('/', 'HomeController@index');

// Route::get('/about', 'GuestController@aboutUs');

// Route::get('/contact-us', 'GuestController@contactUs');

// Route::post('/contact-us/submit', 'GuestController@submitContactUs');

// Route::get('/book-detail/{id}', 'GuestController@detail');

/*Route::get('/read/{id}', [
    'middleware' => ['auth', 'role:member'],
    'uses'       => 'GuestController@read'
  ]);*/

Route::get('/search', 'SearchController@index');

Route::get('/category/{id}', 'SearchController@category');

Auth::routes();
Route::get('auth/verify/{token}', 'Auth\RegisterController@verify');
Route::get('auth/send-verification', 'Auth\RegisterController@sendVerification');

Route::get('/home', 'HomeController@index');
Route::get('settings/profile', 'SettingsController@profile');
Route::get('settings/profile/edit', 'SettingsController@editProfile');
Route::post('settings/profile', 'SettingsController@updateProfile');
Route::get('settings/password', 'SettingsController@editPassword');
Route::post('settings/password', 'SettingsController@updatePassword');

Route::get('manageMailChimp', 'MailChimpController@manageMailChimp');
Route::post('subscribe', ['as'=>'subscribe','uses'=>'MailChimpController@subscribe']);
Route::post('sendCompaign', ['as'=>'sendCompaign','uses'=>'MailChimpController@sendCompaign']);

Route::group(['prefix' => 'master-data', 'middleware'=>['auth', 'role:admin']], function() {
    
    Route::resource('companies', 'CompanyController');
    Route::resource('employees', 'EmployeeController');
    Route::resource('departments', 'DepartmentController');
    Route::resource('employee-types', 'EmployeeTypeController');
    Route::resource('banks', 'BankController');
    Route::resource('currency-types', 'CurrencyTypeController');
    Route::resource('bank-accounts', 'BankAccountController');
    
});

Route::group(['prefix'=>'admin', 'middleware'=>['auth', 'role:admin']], function () {

    
  // Route::resource('authors', 'AuthorsController');
  
  // Route::resource('books', 'BooksController');

  // Route::resource('items', 'ItemController');

  // Route::resource('medicines', 'MedicineController');
  
  // Route::resource('members', 'MembersController');

  // Route::post('members/change-status/{id}', 'MembersController@changeStatus')->name('members.changeStatus');

  // Route::resource('categories', 'CategoriesController');
  
  /*Route::get('statistics', [
    'as'   => 'statistics.index',
    'uses' => 'StatisticsController@index'
  ]);*/

/*  Route::get('export/books', [
    'as'   => 'export.books',
    'uses' => 'BooksController@export'
  ]);*/

/*  Route::post('export/books', [
    'as'   => 'export.books.post',
    'uses' => 'BooksController@exportPost'
  ]);*/

/*  Route::get('template/books', [
    'as'   => 'template.books',
    'uses' => 'BooksController@generateExcelTemplate'
  ]);*/

/*  Route::post('import/books', [
    'as'   => 'import.books',
    'uses' => 'BooksController@importExcel'
  ]);*/
  
});

/*Route::get('books/{book}/borrow', [
  'middleware' => ['auth', 'role:member'],
  'as'         => 'guest.books.borrow',
  'uses'       => 'BooksController@borrow'
]);*/

/*Route::put('books/{book}/return', [
  'middleware' => ['auth', 'role:member'],
  'as'         => 'member.books.return',
  'uses'       => 'BooksController@returnBack'
]);*/

app/Models/Master/Bank.php
<?php

namespace App\Models\Master;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Bank extends Model
{
	use SoftDeletes;

	protected $dates = ['deleted_at'];

	protected $table = 'mst_bank';

	protected $fillable = ['code', 'name'];

	public static function getDropdownListAll()
	{
		return self::pluck('name', 'id')->all();
	}

    
}

app/Http/Controllers/BankController.php
<?php

namespace App\Http\Controllers;

use App\Models\Master\Bank;
use Illuminate\Http\Request;

use Yajra\Datatables\Html\Builder;
use Yajra\Datatables\Datatables;
use Session;

class BankController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request, Builder $htmlBuilder)
    {
        if ($request->ajax()) {
            $banks = Bank::get();
            
            return Datatables::of($banks)
                ->addIndexColumn()
                ->addColumn('action', function($bank){
                    return view('datatable._action', [
                        'model'           => $bank,
                        'form_url'        => route('banks.destroy', $bank->id),
                        'edit_url'        => route('banks.edit', $bank->id),
                        'confirm_message' => 'Yakin mau menghapus ' . $bank->name . '?'
                    ]);
                })                
                ->make(true);
        }

        return view('banks.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('banks.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'code'=> 'required|unique:mst_company',
            'name' => 'required|unique:mst_company',
        ]);
        $bank = Bank::create($request->all());
        Session::flash("flash_notification", [
            "level"=>"success",
            "message"=>"Berhasil menyimpan $bank->name"
        ]);
        return redirect()->route('banks.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Master\Bank  $bank
     * @return \Illuminate\Http\Response
     */
    public function show(Bank $bank)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Master\Bank  $bank
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $bank = Bank::find($id);
        return view('banks.edit')->with(compact('bank'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Master\Bank  $bank
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $bank = Bank::find($id);
        $bank->update($request->only('code', 'name'));
        Session::flash("flash_notification", [
            "level"=>"success",
            "message"=>"Berhasil menyimpan $bank->name"
        ]);

        return redirect()->route('banks.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Master\Bank  $bank
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $bank = Bank::find($id);
        $bank->delete();

        /*if ($member->hasRole('member')) {
            $member->delete();
            Session::flash("flash_notification", [
                "level"=>"success",
                "message"=>"Member berhasil dihapus"
            ]);
        }*/

        return redirect()->route('banks.index');
    }
}

resources/views/banks/_form.blade.php
<div class="box-body">
  <input name="_token" type="hidden" value="{{ csrf_token() }}">
  <div class="form-group has-feedback {{ $errors->has('code') ? ' has-error' : '' }}">
    <label for="code" class="col-sm-2 control-label">Code</label>
    <div class="col-sm-10">
      {{-- <input type="text" name="code" class="form-control" id="code" placeholder="Company Code"> --}}
      {!! Form::text('code', null, ['class'=>'form-control', 'id'=> 'code', 'placeholder'=> 'Bank Code']) !!}
      {!! $errors->first('code', '<span class="help-block">:message</span>') !!}
    </div>
  </div>
  <div class="form-group has-feedback {{ $errors->has('name') ? ' has-error' : '' }}">
    <label for="name" class="col-sm-2 control-label">Bank</label>
    <div class="col-sm-10">
      {{-- <input type="text" name="name" class="form-control" id="name" placeholder="Company Name"> --}}
      {!! Form::text('name', null, ['class'=>'form-control', 'id'=> 'name', 'placeholder'=> 'Bank Name']) !!}
      {!! $errors->first('name', '<span class="help-block">:message</span>') !!}
    </div>
  </div>
</div>
<!-- /.box-body -->
<div class="box-footer">
  <!-- <button type="submit" class="btn btn-default">Cancel</button> -->
  <button type="submit" class="btn btn-info pull-right">Submit</button>
</div>
<!-- /.box-footer -->

resources/views/banks/create.blade.php
@extends('base.admin')

@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Department
    <small>Master Data</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Master Data</a></li>
    <li><a href="{{ route('employee-types.index') }}"></i> Department</a></li>
    <li class="active">Add Record</li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
  <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header with-border">
              <h3 class="box-title">Add New Department</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <div class="col-md-6">
                <!-- Horizontal Form -->
                <!-- form start -->
                <form class="form-horizontal" action="{{ route('banks.store') }}" method="post">
                  @include('banks._form')
                </form>
                <!-- form end -->
              </div>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->

          
        </div>
        <!-- /.col -->
      </div>
</section>
<!-- /.content -->
@endsection

resources/views/banks/edit.blade.php
@extends('base.admin')

@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Banks
    <small>Master Data</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Master Data</a></li>
    <li><a href="{{ route('banks.index') }}"></i> Banks</a></li>
    <li class="active">Add Record</li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
  <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header with-border">
              <h3 class="box-title">Edit Bank</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <div class="col-md-6">
                <!-- Horizontal Form -->
                <!-- form start -->
                {{-- <form class="form-horizontal" action="{{ route('companies.update') }}" method="put"> --}}
                {!! Form::model($bank, ['url' => route('banks.update', $bank->id), 'method' => 'put', 'class'=>'form-horizontal']) !!}
                  @include('banks._form')
                 {!! Form::close() !!}
                {{-- </form> --}}
                <!-- form end -->
              </div>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->

          
        </div>
        <!-- /.col -->
      </div>
</section>
<!-- /.content -->
@endsection

resources/views/banks/index.blade.php
@extends('base.admin')

@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Banks
    <small>Master Data</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Master Data</a></li>
    <li class="active">Banks</li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
  <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <!-- <h3 class="box-title">Companies</h3> -->
            <a href="{{ route('banks.create') }}"><button type="button" class="btn btn-primary btn-sm"> Add New</button></a>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="banks-datatable" class="table table-bordered table-hover">
                <thead>
                <tr>
                  <th>No.</th>
                  <th>Kode</th>
                  <th>Bank</th>
                  <th>Action</th>
                </tr>
                </thead>                
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->

          
        </div>
        <!-- /.col -->
      </div>
</section>
<!-- /.content -->
@endsection

@section('scripts')
<!-- page script -->
  <script>
    $(function() {
        $('#banks-datatable').DataTable({
            processing: true,
            serverSide: true,
            ajax: '{!! route('banks.index') !!}',
            columns: [
                { data: 'DT_Row_Index', orderable:false, searchable:false },
                { data: 'code', name: 'code' },
                { data: 'name', name: 'name' },
                { data: 'action', name: 'action', orderable: false, searchable:false }
            ]
        });
    });
  </script>
@endsection